# Site settings
title: Zachary A. McGee
email: zmcgee@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a PhD student in the Department of Government at the University of Texas at Austin.
  My research interests include the U.S. Congress, political parties, policy process, and elections.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://zacharymcgee.net" # the base hostname & protocol for your site
twitter_username:
github_username:  zacmcgee
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
