# Site settings
title: Biodiversity Risk
email:  
description: This website provides biodiversity news and exposures metrics.
url:  
googlescholar:  
orcid:  
github_username:   
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
