# Site settings
title: Zachary A. McGee
email: zmcgee@stlawu.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a Visiting Assistant Professor in the Department of Government at St. Lawrence University.
  My research interests include the U.S. Congress, political parties, intraparty factions, agenda setting, the policy process, and social network analysis.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://zacharymcgee.net" # the base hostname & protocol for your site
googlescholar: "https://scholar.google.com/citations?user=wlRQLtwAAAAJ&hl=en"
orcid: "https://orcid.org/0000-0002-2462-0269"
github_username:  zacmcgee
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
